name: Deploy Storybook to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "packages/**"
  pull_request:
    branches: [main]
    paths:
      - "packages/**"

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "packages/ai-ui-kit/package-lock.json"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: |
          cd packages/ai-ui-kit
          npm ci

      - name: Install Playwright browsers
        run: |
          cd packages/ai-ui-kit
          npx playwright install --with-deps

      - name: Run Vitest tests with coverage
        run: |
          cd packages/ai-ui-kit
          npm run test:unit -- --run --coverage

      - name: Run Playwright tests
        run: |
          cd packages/ai-ui-kit
          npm run test:e2e

      - name: Upload Playwright HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: packages/ai-ui-kit/playwright-report/
          retention-days: 30

      - name: Upload Vitest Coverage Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: vitest-coverage
          path: packages/ai-ui-kit/coverage/
          retention-days: 30

      - name: Vitest Coverage Report
        uses: davelosert/vitest-coverage-report-action@v2.8.3
        if: github.event_name == 'pull_request'
        with:
          working-directory: packages/ai-ui-kit
          json-summary-path: coverage/coverage-summary.json
          json-final-path: coverage/coverage-final.json

      - name: Playwright Report Summary
        uses: daun/playwright-report-summary@v3
        if: always() && github.event_name == 'pull_request'
        with:
          report-file: packages/ai-ui-kit/playwright-results.json
          comment-title: "Playwright Test Results"

      - name: Build Storybook
        if: github.ref == 'refs/heads/main'
        run: |
          cd packages/ai-ui-kit
          npm run build-storybook

      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/ai-ui-kit/storybook-static

  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
